name: Update gist with WakaTime stats
on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches: 
      - master
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Update gist
        uses: matchai/waka-box@master
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GIST_ID: c20cd94b9ffd8d44d8faa91695fb151a
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
